# Generated by Django 5.0.6 on 2024-07-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubInstagramMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.CharField(db_index=True, max_length=100)),
                ('media_id', models.CharField(max_length=50, unique=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('media_type', models.CharField(max_length=20)),
                ('media_url', models.URLField()),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('permalink', models.URLField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
