# Generated by Django 5.0.1 on 2024-01-22 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubDetail',
            fields=[
                ('clubId', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('clubName', models.CharField(max_length=255)),
                ('clubDescription', models.TextField()),
                ('clubCoverImage', models.ImageField(blank=True, null=True, upload_to='club_covers/')),
                ('clubLogo', models.ImageField(blank=True, null=True, upload_to='club_logos/')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('facebookUrl', models.CharField(blank=True, max_length=255, null=True)),
                ('instagramUrl', models.CharField(blank=True, max_length=255, null=True)),
                ('twitterUrl', models.CharField(blank=True, max_length=255, null=True)),
                ('clubCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Club.category')),
            ],
        ),
    ]
