# Generated by Django 5.0.1 on 2024-01-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0002_clubdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubdetail',
            name='clubCategory',
        ),
        migrations.AddField(
            model_name='clubdetail',
            name='clubCategories',
            field=models.ManyToManyField(blank=True, to='Club.category'),
        ),
    ]
