# Generated by Django 5.0.1 on 2024-01-22 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0003_remove_clubdetail_clubcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubdetail',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='clubdetail',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True),
        ),
        migrations.CreateModel(
            name='ClubEvent',
            fields=[
                ('eventId', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('eventName', models.CharField(max_length=255)),
                ('eventStartDate', models.DateField()),
                ('eventStopDate', models.DateField()),
                ('eventDescription', models.TextField()),
                ('eventCoverImage', models.ImageField(blank=True, null=True, upload_to='event_covers/')),
                ('eventVideo', models.FileField(blank=True, null=True, upload_to='event_videos/')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Club.clubdetail')),
            ],
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event_images/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Club.clubevent')),
            ],
        ),
    ]
