# Generated by Django 5.0.1 on 2024-01-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0004_alter_clubdetail_lat_alter_clubdetail_lon_clubevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubdetail',
            name='clubCoverImage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clubdetail',
            name='clubLogo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clubevent',
            name='eventCoverImage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clubevent',
            name='eventVideo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
